server:
  port: 7777
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/weather-app
    username: root
    password: Punitpunde@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

weather:
  cities:
    - Delhi
    - Bangalore
    - Chennai
